import os

S3_BUCKET_NAME = os.environ.get("S3_BUCKET_NAME")

AWS_REGION = os.environ.get("REGION_AWS")

DYNAMO_TABLE_NAME = os.environ.get("VIDEOS_TABLE_NAME")

FEED_URL = os.environ.get("FEED_URL")

ZAPIER_SECRET_KEY = os.environ.get("ZAPIER_SECRET_KEY")

OTEL_DEPLOYMENT_ENVIRONMENT = os.environ.get("OTEL_DEPLOYMENT_ENVIRONMENT")
OTEL_EXPORTER_OTLP_ENDPOINT = os.environ.get("OTEL_EXPORTER_OTLP_ENDPOINT")
GRAFANA_LABS_TOKEN = os.environ.get("GRAFANA_LABS_TOKEN")
